# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish proto to jfrog

on:
  push:
    tags:
      - v**

jobs:
  publish-proto-to-jfrog:
    runs-on: ubuntu-latest
    timeout-minutes: 70

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup JFrog CLI
      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: https://restatedev.jfrog.io

          # Basic authentication credentials
          JF_USER: ${{ secrets.JFROG_USERNAME }}
          JF_PASSWORD: ${{ secrets.JFROG_TOKEN }}

      - name: Publish to JFrog
        run: |
          # Figure out the version
          VERSION=${GITHUB_REF/refs\/tags\/v}
          if [ -z "$VERSION" ]
          then 
            echo "Could not determine the version from GITHUB_REF: $GITHUB_REF"
            exit
          fi
          
          # Compress the file
          tar -czvf proto-$VERSION.tar.gz dev
          
          # Upload to JFrog
          jf rt ping
          jf rt u proto-$VERSION.tar.gz proto-generic-local/dev/restate/proto/